# This workflow starts your API and fuzzes it with ForAllSecure Mayhem for API
# to find reliability, performance and security issues before they reach
# production.
#
# To use this workflow, you will need to:
#
# 1. Create a Mayhem for API account at
#    https://mayhem4api.forallsecure.com/signup (30-day free trial)
#
# 2. Create a service account token `mapi organization service-account create
#    <org-name> <service-account-name>`
#
# 3. Add the service account token as a a secret in GitHub called "MAPI_TOKEN"
#
# 4. Update the "Start your API" step to run your API in the background before
#    starting the Mayhem for API scan, and update the `api-url` & `api-spec`
#    field.
#
# If you have any questions, please contact us at mayhem4api@forallsecure.com

name: "Mayhem for API"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mayhem-for-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Run your API in the background. Ideally, the API would run in debug
      # mode & send stacktraces back on "500 Internal Server Error" responses
      # (don't do this in production though)
      - name: Start your API
        run: ./run_your_api.sh & # <- update this

      # Run Mayhem for API
      - name: Mayhem for API
        uses: ForAllSecure/mapi-action@master
        continue-on-error: true
        with:
          mapi-token: ${{ secrets.MAPI_TOKEN }}
          api-url: http://localhost:8080 # <- update this
          api-spec: http://localhost:8080/openapi.json # <- update this
          duration: 60
          sarif-report: mapi.sarif
          html: mapi.html

      # Archive HTML report
      - name: Archive Mayhem for API report
        uses: actions/upload-artifact@v2
        with:
          name: mapi-report
          path: mapi.html

      # Upload SARIF file (only available on public repos or github
      # enterprise). If you cannot use this action, other report format are
      # available (HTML, JUnit)
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: mapi.sarif

